### PR TITLE
Modification in "As a script", Usage

### PR DESCRIPTION
**Pull request by ykoji8681**
I have installed, but I couldn't find "cli.py".
It should be "stix2_elevator".

### CODE REVIEW

**Comment by rpiazza** [comment]
Thanks - good catch! 
 Yes, the documentation is wrong 

@ykoji8681 have you signed the individual CLA for OASIS?

**Comment by ykoji8681** [comment]
Hi Rich,

I signed the individual CLA today.

Thank you.

2018-06-13 22:23 GMT+09:00 Rich Piazza <notifications@github.com>:

**Comment by robincover** [comment]
The CLA is on file:
https://www.oasis-open.org/resources/open-repositories/cla/view-individual

Contributor Name: Koji Yamada
Contributor Email: ykoji8681@gmail.com
Github Username: ykoji8681

Thanks, Koji Yamada

**Comment by gtback** [comment]
Thanks, @ykoji8681 !

**Pull request merged**
