### PR TITLE
Add additional data validation logic

### PR DESCRIPTION
**Pull request by cipherlock**
- Added additional data validation by checking for the existence of the authority_reference dictionary key
- Ensuring that the prop.layer4_protocol.value has data and not just that the object exists

### CODE REVIEW

**Review by rpiazza — DISMISSED** [review]

**Review by rpiazza — COMMENTED** [review]
The convert_pattern.py change looks good.

The convert_to_acs.py also looks good, except perhaps it exposed an different bug.  Shouldn't 
`acs_marking["authority_reference"] = isa_marking.auth_ref`
be 
`acs_marking["authority_reference"] = [isa_marking.auth_ref]`

Can you look into that?

**Comment by rpiazza** [comment]
@ejratl - I approve these changes, but can no longer approve anything in Github on this repository.

**Comment by cipherlock** [comment]
Screen Shot 2022-08-18 at 10 16 45 AM

**Comment by ejratl** [comment]
@cipherlock hahahahaha too funny
@rpiazza I don't have maintainership rights on this repo
@JasonKeirstead Will you be able to handle this pull request, please?

**Review by JasonKeirstead — APPROVED** [review]
LGTM

**Comment by JasonKeirstead** [comment]
@rpiazza If you can't approve PRs here, should you be removed from https://github.com/oasis-open/cti-stix-elevator/README.md? Can Chris Lenk still approve?

**Comment by ejratl** [comment]
@JasonKeirstead There is a pending PR to do so #284 (from Jul. 13).

**Pull request merged**
