### PR TITLE
Merge pull request #103 from oasis-open/master

### PR DESCRIPTION
**Pull request by rpiazza**
Please generate the read-the-docs and review them, in addition to reviewing the code

### CODE REVIEW

**Comment by rpiazza** [comment]
@emmanvg and @gtback:

I'm not exactly sure what happened.  I tried to separate the doc and code commits, and got into a heap of trouble.  Actually, I think I inadvertently committed these changes to the master branch already :-(.

Anyway - the code commit is 7a9633d and the doc commits are https://github.com/oasis-open/cti-stix-elevator/commit/242ea744f1aed5c17ad2526e43073355979f33ed, and https://github.com/oasis-open/cti-stix-elevator/commit/3f7da73735f3dfae4988dffbac5906864507ff50

I guess the best way to review the docs is to run "make html" and review the local files?

Also, @gtback - do we just update the read-the-docs site by hand once this PR is merged in?

**Comment by gtback** [comment]
Somehow git got confused; the only changes in this PR are to setup.py, and aren't changes we want (I don't think).

@rpiazza, ReadTheDocs should detect any commits to the master branch (via a webhook) and rebuild the documentation automatically.

**Comment by emmanvg** [comment]
@gtback I think we do need these changes. Look at the setup file in master https://github.com/oasis-open/cti-stix-elevator/blob/master/setup.py. It has duplicate `entry_points` and `install_requires`

**Comment by gtback** [comment]
Good catch @emmanvg ! I didn't realize it was duplicated.

**Pull request merged**
