### PR TITLE
Add codecov and git hooks configuration.

### PR DESCRIPTION
**Pull request by emmanvg**
Some functionality to add to the project. This should help in maintaining good quality of the code across all CTI repos.

### CODE REVIEW

**Comment by gtback** [comment]
I'm not sure why the builds are now failing. I'll check to see if some updated dependency caused a regression, since I don't see anything specifically in this PR that would cause problems.

**Comment by emmanvg** [comment]
I excluded xml and json files from the checks of the pre-commit tools.

**Comment by emmanvg** [comment]
@gtback, do you have any idea why codecov is generating reports using the wrong file?
https://travis-ci.org/oasis-open/cti-stix-elevator/jobs/278656657#L1061

**Comment by gtback** [comment]
I think it might be related to the fact that we don't have coverage data on the master branch. Since you fixed the recursion thing, I'll go ahead and merge this in, then update the other PRs to use it.

**Pull request merged**
